version: '3.4'

services:
  csoketlso:
    image: csocketlso
    build:
      context: .
      dockerfile: ./Dockerfile
    networks:
      - LSO
    ports:
      # Range of ports for the server
      - "3000-3010:3000-3010"
    depends_on:
      - db
      
  db:
    container_name: lsodb
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: default
      POSTGRES_DB: postgres
    networks:
      - LSO
    volumes:
      - dbdata:/var/lib/postgresql/data
    
volumes:
  dbdata:
    driver: local

networks:
  LSO:
    driver: bridge
