version: '3.1'

services:
  db:
    container_name: lsodb
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: default
      POSTGRES_DB: postgres
    networks:
      - LSO

networks:
  LSO:
    driver: bridge
