# Commento: istruzione per l'immagine di base
FROM ubuntu:latest

# Crea una directory all'interno del container
RUN mkdir -p /usr/local/bin/server

# Copia i file del server nel container
COPY LSOProject /usr/local/bin/server/

# Esponi la porta su cui il server sarà in ascolto
EXPOSE 3000-4000

# Esponi la porta su cui il server si collegherà al database
EXPOSE 5432

# Aggiungi il percorso del server all'ambiente
ENV PATH="${PATH}:/usr/local/bin/server"

# Imposta la directory di lavoro
WORKDIR /usr/local/bin/server

# Aggiungi permesso di esecuzione ad LSOProject
RUN chmod +x LSOProject

# Comando predefinito per avviare il server quando il container viene eseguito
CMD ["LSOProject"]